apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
spec:
  type: pubsub.kafka
  version: v1
  metadata:
  - name: brokers # Required. Kafka broker connection setting
    value: "kafka:9092"
  - name: authType # Required.
    value: "none"
  - name: disableTls # Optional. Disable TLS. This is not safe for production!! You should read the `Mutual TLS` section for how to use TLS.
    value: "false"
  - name: publishingScopes
    value: "checkoutservice=orders"
  - name: subscriptionScopes
    value: "accountingservice=orders;frauddetectionservice=orders"
scopes:
- accountingservice
- checkoutservice
- frauddetectionservice